name: Build Android Debug APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pega o código do repositório
      - name: Checkout código
        uses: actions/checkout@v4

      # 2️⃣ Configura Java 17 (necessário para Android 34)
      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Permite executar gradlew
      - name: Permitir execução do Gradlew
        run: chmod +x ./gradlew

      # 4️⃣ Build do debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 5️⃣ Upload do APK como artefato para download
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
